### ISSUE TITLE
Display plugin as possible execution in list of alternatives

### ISSUE THREAD

**Issue by kominoshja** [mesutpiskin/keycloak-2fa-email-authenticator#50]
When multiple keycloak executions are set as alternative for one another, keycloak will display a "Try Another Way" button below the blue action button.

As of right now, even if set to be an alternative execution, this plugin isn't exposed as a possible option.

Flow (relevant part):
![image](https://github.com/user-attachments/assets/3ca1f105-1d4c-447f-b46b-533a390ced35)

Email OTP Alternative not being selectable by the user:
![image](https://github.com/user-attachments/assets/3f61a201-337c-4b6b-ac0c-b544b0e39316)

**Comment by beezerk23** [comment]
@kominoshja You found any solution to this? When i use it as alternative it just skips the selection screen and goes straight to the email one

**Comment by kominoshja** [comment]
@beezerk23 No, I imagine something needs to be updated in the codebase, but haven't investigated much further.

**Comment by mittflo** [comment]
@kominoshja Currently looking for something like this too. What I found was another plugin that supports this, but sadly, it doesn’t work with this one. However, they also offer an SMS OTP feature if that’s of any interest.

https://github.com/netzbegruenung/keycloak-mfa-plugins/tree/main/enforce-mfa

**Comment by aljavier** [comment]
I have a similar flow and it does show up, could it be that you need to tweak a little bit your flow? You have like a subflow under a subflow, in my case I have 3 multifactor methods: authenticator, passkeys stuff and email. 

Check my images below.

<img width="1565" height="562" alt="Image" src="https://github.com/user-attachments/assets/54efc368-1b1e-4a72-becc-877621b36327" />
**Note:** For my use case, I still need to change above flow, to make email conditional to a role or something like that and see if it will work with this code.


After I clicked **"Try Another Way"** link

<img width="601" height="624" alt="Image" src="https://github.com/user-attachments/assets/857c16a2-84f6-4e87-a15e-acf4508da0a0" />

For some reason on my Keycloak I am using for testing this out (a docker image with Keycloak 26.4.7), it does not show the icons near each entry, but you can see clearly that the Email Authenticator is there.

**Comment by moberwasserlechner** [comment]
I'm running KC 26.4.7 with buildin themes and I tried the same authentication flow as @aljavier.

But after entering username and password the email otp form is shown immediately. There is no button "Try Another Way" or this "Select login method" page shown.

@aljavier On which page does the "Try another way" button appear in your KC 26.4.7 setup?

<img width="1465" height="820" alt="Image" src="https://github.com/user-attachments/assets/5ff09810-0079-48ad-902c-bc16873799b5" />

**Comment by moberwasserlechner** [comment]
@aljavier Thanks! Looking at your screenshots I found the difference.

In my case the user does not have any MFA methods configured. We want users to choose equally between all MFA methods. So if the user only wants to use email-mfa they are not forced to setup app-mfa as well and vice versa.

I think PR #86 addresses this.

I can reproduce your behavior though, if I setup the Authenticator App by a required action = CONFIGURE_TOTP and login afterwards I see the "Try another way" on both forms.

email
<img width="706" height="466" alt="Image" src="https://github.com/user-attachments/assets/47c52aba-d28d-4679-bb00-efcb4b28ccc0" />

app
<img width="636" height="474" alt="Image" src="https://github.com/user-attachments/assets/dbb45c30-b03d-4204-95d6-b5ea3b9d37ca" />

Do you mind testing your flow with a user that does not have Authenticator App or Webauthn setup yet. I would guess you have the same behavior as me and @beezerk23

**Comment by Dunge** [comment]
Hello, I'm trying to do the same (let the user decide the mfa choice).
No matter what I do, after entering the user/pass, it ALWAYS automatically go to the email setup with no other choice.

Yes I have the flow correctly selected in my client flow choice, and both enabled in the auth actions menu.

What am I missing?

<img width="1085" height="999" alt="Image" src="https://github.com/user-attachments/assets/31d423f6-6461-46aa-9e31-f4508d466f81" />

KC 26.5.0 with email plugin 26.1

edit: Well it seems to go with the "required user actions" set on the user. If I set "Configure OTP", it opens the app QR page, if I set "Set up email" it opens the email page. If I set both it also opens the email page. How can I let him choose?

**Comment by mesutpiskin** [comment]
This is fixed in PR #128.

**Root cause**: The "Try Another Way" button lists alternatives where `isConfiguredFor()` (or `configuredFor()`) returns `true`. `EmailAuthenticatorCredentialProvider.isConfiguredFor()` only checked the stored credential. Users without a stored credential (i.e., those who haven't gone through explicit enrollment) would not appear as an available alternative.

**Fix**: `isConfiguredFor()` now additionally checks the `skipSetup` configuration and the user's email. When `skipSetup=true` (the default) and the user has an email address, the method returns `true` — no stored credential needed. This makes the email OTP authenticator appear correctly in the "Try Another Way" selection list.

The fix will be in release **v26.3.1**.

**Comment by Qparrot** [comment]
Hello ,

Thank you for this package.

I am currently using the version 26.4.1 of the package with Keycloak 26.6.2 and still having difficulty displaying the list of alternatives.

## Context

A user can have:

- both authenticator app 2FA and email 2FA configured
- only authenticator app 2FA configured
- only email 2FA configured
- no 2FA configured

We also implemented a role that forces 2FA usage.

Our expected behavior is the following:

- only one successful 2FA validation should be required
- the Email OTP option should be displayed first
- when both 2FA methods are enabled, the OTP Form and the Email OTP Form page should display a tryAnotherWay button allowing users to switch between App-based OTP and Email OTP authentication


## Problem


The issue occurs in the first case (when both methods are configured).

With the following authentication flow configuration, specifically in the subflow `Email and App Authenticator Enabled`, the only method initially displayed is the OTP Form (authenticator app).

In addition, when clicking the `Try another way` button, the only available option is again the OTP Form.

```flow
[FLOW][ALTERNATIVE] Browser Forms
↳ [STEP][REQUIRED] Username Password Form
↳ [FLOW][CONDITIONAL] 2FA Enforcement Flow
     ↳ [CONDITION][REQUIRED] Condition - user role
     ↳ [STEP][REQUIRED] Force 2FA setup Choice 
 ↳ [FLOW][REQUIRED] Two-Factor Authentication
      ↳ [FLOW][ALTERNATIVE] 2FA Method Router: Email or App
           ↳ [FLOW][CONDITIONAL]Email and App Authenticator Enabled
                ↳ [CONDITION][REQUIRED] Condition - Email 2FA Enabled
                ↳ [CONDITION][REQUIRED] Condition - user configured
                ↳ [STEP][ALTERNATIVE] Email OTP Form
	            ↳ [STEP][ALTERNATIVE] OTP Form
      ↳ [FLOW][ALTERNATIVE] 2FA Method Router: Email-Only
           ↳ [FLOW][CONDITIONAL] Email-Only Authenticator Enabled
                ↳ [CONDITION][REQUIRED] Condition - Email 2FA Enabled
                ↳ [STEP][REQUIRED] Email OTP Form
      ↳ [FLOW][ALTERNATIVE] 2FA Method Router: App-Only
           ↳ [FLOW][CONDITIONAL] App-Only Authenticator Enabled
                ↳ [CONDITION][REQUIRED] Condition - user configured
                ↳ [STEP][REQUIRED] OTP Form
      ↳ [FLOW][ALTERNATIVE] 2FA Method Router: 2FA Disabled
           ↳ [STEP][REQUIRED] Allow access
```

## Additional investigation

To verify whether the issue could come from my keycloak configuration, I also tested a concurrent package implementing a similar Email OTP feature:

[for-keycloak/email-otp-authenticator](https://github.com/for-keycloak/email-otp-authenticator)

With this package, the flow behaves almost as expected:

- users can switch between Email OTP and App OTP
- both methods are available through `Try another way`

However, the OTP Form still appears first in the authentication flow:

[Issue #84 - OTP Form comes first in "TryAnotherWay" scope](https://github.com/for-keycloak/email-otp-authenticator/issues/84)

Because of this, I am wondering whether the problem could actually come from a limitation or internal behavior of Keycloak itself rather than from this package implementation. Maybe as described [here](https://github.com/keycloak/keycloak/issues/39067)

## Question

Is this expected behavior, a limitation of the package, a bug or my mistake?

## Additional information

Package version: 26.4.1
Keycloak version: 26.6.2

Thank you for your help.

Best regards

**Comment by ismailza** [comment]
Hi @Qparrot 👋,

## Root cause

This is a **Keycloak core behavior**, not a bug in this package.

In Keycloak 26.x, the 2FA method displayed first at login is **not determined by the authentication flow execution order**, but by the user’s **credential priority/order**.

Internally, this is driven by the credential’s `priority` (when set). If no explicit priority exists, Keycloak falls back to **enrollment order**, meaning the first registered credential is typically selected as the default.

## Empirical confirmation (tested on Keycloak 26.6.1)

I ran additional tests to validate this behavior:

### Observations
- I created two users with multiple 2FA methods (App OTP and Email OTP), but with different enrollment orders.
- At login, Keycloak consistently shows the **first configured 2FA method for each user as the default option**.
- I also manually changed the **credential order in the user’s Credentials section (Admin Console)**.

### Result
After reordering credentials for a user, the **first credential in the list becomes the default 2FA method shown during authentication**, regardless of the authentication flow configuration.

### Conclusion
In Keycloak 26.6.1:

- Authentication flows define which 2FA methods are available
- The **user credential order (priority / enrollment order fallback)** determines which method is selected by default
- Flow execution order does not control the default MFA method once multiple credentials exist

So the behavior described here is consistent with Keycloak's credential selection logic.

Hope this helps clarify the situation!

**Comment by mesutpiskin** [comment]
Hi @kominoshja — apologies for the long wait on this one. The plugin wasn't appearing in "Try Another Way" because `EmailAuthenticatorForm.configuredFor` was returning `false` for any user without a stored `email-authenticator` credential, and Keycloak hides alternatives whose authenticator reports they aren't configured for the user.

Fixed in #136 (released as [v26.4.2](https://github.com/mesutpiskin/keycloak-2fa-email-authenticator/releases/tag/v26.4.2)).

**What changed**

- `EmailAuthenticatorForm.configuredFor` now returns `true` for any user with a non-blank email. No explicit enrolment is required for the plugin to register itself as a valid alternative — which is the natural semantic for email OTP, since the email address itself is the only credential needed.
- The plugin now shows up in the "Try Another Way" list as soon as the user has an email on their account.

Closing — please pull v26.4.2 and verify in your setup. Reopen if the alternative still doesn't surface in your flow configuration.

**Comment by EugeneQilo** [comment]
@mesutpiskin, first thank you for your work.

This is still not working for me, I tried multiple workflow combinations nothing is working. Try another way doesn't show along with Authenticator OTP or Passkey

<img width="1398" height="612" alt="Image" src="https://github.com/user-attachments/assets/fdcb5f8c-28f4-4c71-8b7f-b3fed79e7c82" />

I can confirm the user has email since I have email as username enabled

<img width="219" height="201" alt="Image" src="https://github.com/user-attachments/assets/6cfe72df-a6fe-45ef-bed5-4fa4c98b046e" />

There is a small chance that my issue is related to upgrade scenario
* I was using v26.4.1 with KC26.5.1, I played around with adding the steps and "skip setup" 
* Once I found this, without removed prior Email OTP I upgraded to v26.4.2 with KC26.5.1. I cannot get the "Try another way" to work no matter what I do.

I would appreciate your help on this

**Comment by Qparrot** [comment]
Hi @ismailza,

Thank you for your explanation. It really helped me understand how the ordering works. I retried your experiment on my side and got the same results!

I updated the provider to version 26.4.3, and it now works like a charm. I configured 2FA with email, and on the "Try another way" page, both OTP methods are now available:

- Email
- Authenticator app

Thanks to the v26.4.3 update, my authentication flow is now much simpler:

```
[FLOW][ALTERNATIVE] Browser Forms
↳ [STEP][REQUIRED] Username Password Form
↳ [FLOW][CONDITIONAL] 2FA Enforcement Flow
    ↳ [CONDITION][REQUIRED] Condition - User Role
    ↳ [STEP][REQUIRED] Force 2FA Setup Choice
↳ [FLOW][CONDITIONAL] Two-Factor Authentication
    ↳ [CONDITION][REQUIRED] Condition - User Configured
    ↳ [STEP][ALTERNATIVE] Email OTP Form
    ↳ [STEP][ALTERNATIVE] OTP Form
```

Since credential ordering is a core Keycloak feature, I use the Keycloak Admin API to allow users to change the order of their authentication methods.

Current versions:

Keycloak: 26.6.2
keycloak-2fa-email-authenticator: 26.4.3

@EugeneQilo, maybe you've already solved your issue. If not, you can try these versions and the authentication flow above and see if the "Try another Way" button appears.
